### PR TITLE
Fix backspace when selecting multiple blocks in the same cell

### LINKED ISSUE #77: Backspace with selecting multiples blocks in a cell clear the whole cell
Pressing <kbd>Backspace</kbd> when selecting multiple blocks in the same cell clear the entire cell.

Because of https://github.com/GitbookIO/slate-edit-table/blob/master/lib/handlers/onBackspace.js#L33

### PR DESCRIPTION
**Pull request by SamyPesse**
This PR fixes #77.

### CODE REVIEW

**Comment by Soreine** [comment]
I just added two tests to check it's working as expected.
I also simplified the first condition

File: lib/handlers/onBackspace.js [hunk 1]
```diff
@@ -13,24 +13,21 @@ function onBackspace(
...
         block => block.key == startBlock.key
     );
 
     // If a cursor is collapsed at the start of the first block, do nothing
-    if (startOffset === 0 && isCollapsed) {
-        if (startBlockIndex > 0) {
-            // Normal deletion
-            return undefined;
-        }
-
```
Comment (Soreine) [inline lib/handlers/onBackspace.js]: I simplified this first condition
