### PR TITLE
Keyboard interactions for multi-blocks in table cells

### LINKED ISSUE #3: Pressing Enter in a cell should split the text

### LINKED ISSUE #70: Backspace behavior with multiple blocks
The "backspace" key doesn't work as expected when a cell contains multiple blocks.

### LINKED ISSUE #71: Enter key doesn't split blocks
Pressing enter in a cell doesn't split the block but inserts a new row.

### PR DESCRIPTION
**Pull request by SamyPesse**
- [x] Split block when pressing <kbd>Shift+Enter</kbd> (Fix #71 )
- [x] Split block when pressing <kbd>Enter</kbd> inside the cell (Fix #3)
- [x] UP/DOWN doesn't move cursor across rows if there's a block after or before the cursor
- [x] <kbd>Backspace</kbd> should correctly let you delete a block
- [x] <kbd>Backspace</kbd> should correctly delete cells with multiple blocks (Fix #70)

### CODE REVIEW

File: lib/handlers/onBackspace.js [hunk 1]
```diff
@@ -11,10 +11,20 @@ function onBackspace(
...
-    // If a cursor is collapsed at the start of the block, do nothing
+    const cell = document.getParent(startBlock.key);
+    const startBlockIndex = cell.nodes.findIndex(
+        block => block.key == startBlock.key
+    );
+
+    // If a cursor is collapsed at the start of the first block, do nothing
     if (startOffset === 0 && isCollapsed) {
+        if (startBlockIndex > 0) {
+            // Normal deletion
```
Comment (Soreine) [inline lib/handlers/onBackspace.js]: This check should be done earlier. We want normal deletion even if the selection is not collapsed to the start of a block.

Comment (Soreine) [reply lib/handlers/onBackspace.js]: You haven't added any test in this PR. Let's add a test for this.

File: lib/handlers/onBackspace.js [hunk 2]
```diff
@@ -28,13 +38,13 @@ function onBackspace(
...
 
-    const { blocks, document } = value;
+    const { blocks } = value;
     const getAncestorCell = node =>
         node.type === opts.typeCell
             ? node
             : document.getClosest(node.key, a => a.type === opts.typeCell);
     const cells = blocks.map(getAncestorCell).toSet();
-    cells.forEach(cell => clearCell(opts, change, cell));
+    cells.forEach(block => clearCell(opts, change, block));
```
Comment (Soreine) [inline lib/handlers/onBackspace.js]: I'm curious about the need to rename the parameter here

File: lib/handlers/onEnter.js [hunk 3]
```diff
@@ -15,6 +15,12 @@ function onEnter(
 ): void | Change {
     event.preventDefault();
 
+    if (event.shiftKey) {
+        return change
+            .splitBlock()
+            .setBlocks({ type: opts.typeContent, data: {} });
```
Comment (Soreine) [inline lib/handlers/onEnter.js]: Have you checked that it works with a selection expanded as well ?

Comment (Soreine) [reply lib/handlers/onEnter.js]: It would be cool to have 2 tests for these cases.

File: lib/handlers/onUpDown.js [hunk 4]
```diff
@@ -22,9 +22,18 @@ function onUpDown(
         // Let the default behavior move out of the table
         return undefined;
     }
+
+    if (direction < 0 && !pos.isTopOfCell()) {
```
Comment (Soreine) [inline lib/handlers/onUpDown.js]: Checking for `direction === -1` won't mislead into thinking that `direction` can be any negative number

File: lib/utils/TablePosition.js [hunk 5]
```diff
@@ -31,12 +35,24 @@ class TablePosition extends Record({
...
+            p => p.type === opts.typeCell
+        );
+
+        // Skip all ancestors until the current cell
+        const cellsAndAfter =
+            cellIndex >= 0 ? ancestors.skip(cellIndex) : List();
+
+        // Take the cell and the inner content
+        const cellBlock = cellsAndAfter.first();
+        const contentBlock = cellsAndAfter.skip(1).first();
```
Comment (Soreine) [inline lib/utils/TablePosition.js]: I think I'd prefer it to be written like this

```js
const cellBlock = ancestors.findLast(p => p.type === opts.typeCell);
const contentBlock = ancestors.skipUntil(ancestor => ancestor === cellBlock).skip(1).first();
```

File: tests/backspace-clear-cells-with-multiple-blocks/change.js [hunk 6]
```diff
@@ -0,0 +1,18 @@
...
+        .collapseToStartOf(blockStart)
+        .extendToEndOf(blockEnd);
+
+    return plugin.onKeyDown(
+        {
+            key: 'Backspace',
+            preventDefault() {},
+            stopPropagation() {}
+        },
+        withCursor
```
Comment (Soreine) [inline tests/backspace-clear-cells-with-multiple-blocks/change.js]: You can use `<focus />` and `<anchor />`
